### PR TITLE
#75: Literal pushdown fails

### LINKED ISSUE #75: Pushdown of literal values fails
Executing a simple query with literal values in the select list against a schema from an Oracle virtual schema like 

```sql
select 0 as c1 from oravs.t1;
```

fails with the following error message:

```
[Code: 0, SQL State: 42636] ETL-1299: Failed to create transformator for column=0 (starting from 0 for selected columns) [ETL-1202: Not implemented - Transformation for this combination of column types is not possible in this version.
```

Similar queries also fail:

```sql
select null from oravs.t1;
```

```
[Code: 0, SQL State: 04000]  Adapter generated invalid pushdown query for virtual table A: Data type mismatch in column number 1 (1-indexed). Expected BOOLEAN, but got VARCHAR(2000000) UTF8
```

### Workaround

Set `IMPORT_FROM_ORA = 'false'.` when creating the virtual schema. This may however impact performance.

### PR DESCRIPTION
**Pull request by kaklakariada**
Closes #75

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/oracle/OracleQueryRewriter.java [hunk 1]
```diff
@@ -43,16 +41,15 @@ private boolean isGenerateJdbcDatatypeMappingForOCIEnabled() {
...
 
     @Override
     protected String generateImportStatement(final String connectionDefinition,
-                                             List<DataType> selectListDataTypes, final String pushdownQuery) {
-        if (isGenerateJdbcDatatypeMappingForOCIEnabled()) {
+            final List<DataType> selectListDataTypes, final String pushdownQuery) {
+        if (isGenerateJdbcDatatypeMappingForOCIEnabled() && !selectListDataTypes.isEmpty()) {
             final String columnDescription = this.createImportColumnsDescription(selectListDataTypes);
             return "IMPORT INTO (" + columnDescription + ") FROM ORA " + connectionDefinition + " STATEMENT '" + pushdownQuery.replace("'", "''") + "'";
         } else {
```
Comment (kaklakariada) [inline src/main/java/com/exasol/adapter/dialects/oracle/OracleQueryRewriter.java]: The additional condition avoids rendering invalid syntax `IMPORT INTO () FROM ORA` for an empty `selectListDataTypes`.
